import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Header from '@/components/common/Header';
import { Providers } from '@/components/common/Providers';
import Footer from '@/components/common/Footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Mentors system',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <Providers>
                    <Header />
                    <main className="pt-[7rem] bg-content-bg min-h-screen"> {children}</main>
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
