import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { Providers } from '@/components/common/Providers';
import ToastProvider from '@/components/common/ToastProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Mentors system',
    description: 'Generated by create next app',
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <Providers>
                    <main className="bg-content-bg min-h-screen"> {children}</main>
                    <ToastProvider />
                </Providers>
            </body>
        </html>
    );
}
